### ISSUE TITLE
VerifyCallerIsProperty improperly throws error when called from explicitly implemented interface property

### ISSUE THREAD

**Issue by chris-clark** [danielmoore/WpfIgniter#1]
VerifyCallerIsProperty improperly throws and InvalidOperationException when called from explicitly implemented interface property. The following example reproduces the issue:

DateTime ISomeInterface.UpdatedDate
{
    get { return _updatedDate; }
    set { SetProperty(ref _updatedDate, value, "UpdatedDate"); }
}

**Comment by danielmoore** [comment]
Thanks for finding this. I have to admit, explicitly implemented interface properties are a bit strange on view models, but should be supported all the same.

This commit should fix the problem for you: danielmoore@dd716fa5ee9c05851d5829e56bfaf9db2cae4022
